version: '3.8'
services:
  yogabhavana:
    container_name: qrated-yogabhavana-client-container
    build:
      context: ./
      dockerfile: Dockerfile-yogabhavana
    volumes:
        - .:/app-yogabhavana
        - /app-yogabhavana/node_modules
        - /app-yogabhavana/.next
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - APP_ID=1
      - NEXT_PUBLIC_APP_ID=1
  fullstacked:
    container_name: qrated-fullstacked-client-container
    build:
      context: ./
      dockerfile: Dockerfile-fullstacked
    volumes:
        - .:/app-fullstacked
        - /app-fullstacked/node_modules
        - /app-fullstacked/.next
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - APP_ID=2
      - NEXT_PUBLIC_APP_ID=2