
version: '3.9'

services:
  app:
    build: .
    depends_on:
      - dbservice
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app/
      # node_modules workaround for volumes
      # https://stackoverflow.com/a/32785014
      - /usr/src/app/node_modules
    networks:
      - cryptomob-network
  dbservice:
    image: postgres:15-alpine
    ports:
      # Standard port for PostgreSQL databases
      - 5432:5432
    volumes:
      - ./pgvolumes/cryptomob/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cryptomob
    networks:
      - cryptomob-network

networks:
  cryptomob-network: